version: '2'
services:
  helloworld:
    build: .
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY}/helloworld:${TAG}
    ports:
      - "80:80"
    mem_limit: 1024m
    environment:
      - DEBUG=1
      - ANOTHER_SETTING=DUMMY
