version: '2'

services:
   wordpress:
     image: wordpress:latest
     mem_limit: 512m
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: localhost
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: supersecretpassword
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - wp-content:/var/www/html 

   wordpress_cli:
     image: wordpress:cli
     mem_limit: 512m
     restart: always
     environment:
       WORDPRESS_DB_HOST: localhost
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: supersecretpassword
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - wp-content:/var/www/html 

volumes:
  wp-content:
